# .github/workflows/check-merge-queue.yml

name: Check Build After Merge

on:
  merge_group:
    branches: [dev]

jobs:
  build:
    name: After Merge Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu

      - name: Grant Gradle Permission
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build --no-daemon --stacktrace
