name: Check Build After Merge

on:
  pull_request:
  merge_group:
    branches: [dev]

jobs:
  build:
    name: After Merge Build
    if: ${{ github.event_name == 'merge_group' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu
      - run: chmod +x ./gradlew
      - run: ./gradlew build --no-daemon --stacktrace
