name: Validate code in the merge queue

on:
  merge_group:

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Display info
      run: | 
        pwd
        tree -a -I '.git'
        git status
    - name: Run slow CI (emulated by a long sleep)
      id: check
      run:  |
        sleep 10
        exit 1
      continue-on-error: true
    - name: Leave comment on PR
      if: steps.check.outcome == 'failure'
      run: |
        echo "❗ 이전 step 실패 확인됨 → 코멘트 남김"
        exit 1
